// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aabsrogfdsnkktifhpgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhYnNyb2dmZHNua2t0aWZocGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODA1MjEsImV4cCI6MjA3MTk1NjUyMX0.7Pcr9CTWkitNJjJsKojG9wMdAi4dWLCcC5rG-l5nZWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});